version: 2.1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_docker_image:
          context: git

jobs:
  build_docker_image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "${GITHUB_TOKEN}" | docker login ghcr.io -u Jayfesco1 --password-stdin
            docker build --build-arg BUILD_NUM=${CIRCLE_BUILD_NUM}  -t ghcr.io/jayfesco1/picodav:${CIRCLE_BUILD_NUM} -t ghcr.io/jayfesco1/picodav:latest .
            docker push ghcr.io/jayfesco1/picodav:${CIRCLE_BUILD_NUM}
            docker push ghcr.io/jayfesco1/picodav:latest

